import { Poppins } from "next/font/google";
import "./globals.css";
import AppShell from "@/components/global/app-shell";

// Load Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // you can adjust weights as needed
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AppShell>
      <html lang="en">
        <body className={`${poppins.variable} font-sans antialiased`}>
          {children}
        </body>
      </html>
    </AppShell>
  );
}
